import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/Sonner";
import QueryProvider from "@/lib/query-providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          {children}
          <Toaster
            position="top-center"
            richColors
            theme="light"
            toastOptions={{
              classNames: {
                toast:
                  "rounded-xl shadow-lg border border-gray-200 bg-white text-gray-900",
                title: "font-semibold",
                description: "text-sm text-gray-600",
                actionButton:
                  "bg-primary text-white rounded-lg px-3 py-1 hover:bg-primary/90",
                cancelButton: "bg-gray-100 text-gray-700 rounded-lg px-3 py-1",
                success: "border-green-500",
                error: "border-red-500",
                warning: "border-yellow-500",
                info: "border-blue-500",
              },
            }}
          />
        </QueryProvider>
      </body>
    </html>
  );
}
