@baseUrl = http://localhost:5000/api/v1/appointments
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMWYzOTBlNDYtMDdiMy00OTZlLWI2ZjUtYmZiN2QwOWU3ZDYyIiwicm9sZSI6InBhdGllbnQiLCJpc3MiOiJtZWRpbGluay1hcHAiLCJleHAiOjE3Njc5MjA1MDUsImlhdCI6MTc2NzgzNDEwNX0.ov3WCm1WzNqbI-uKl6duD1Sr7O0xcT-tABXPEvfKhPM

###
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
   "email": "irulxartal@gmail.com",
   "password": "SecurePass123"
}

###
GET {{baseUrl}}
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/doctor/d3acd040-75b4-46dc-9cc0-1cbebe986a2b
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/patient/d6dcf46a-6320-4468-8bbc-489e0d2acc19
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/fb206715-cea7-4c3c-b473-35d0e6635414
Authorization: Bearer {{token}}

###
POST {{baseUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "doctor_id": "d877e585-306e-4cb6-a4e5-69d41b5d2428",
  "clinic_id": "03431a76-aed5-4024-a243-23307a07a3d5",
  "schedule_id": "cee738c5-0284-4f88-97dc-df127e6228c5",
  "appointment_date": "2025-01-10",
  "start_time": "09:00",
  "end_time": "09:30",
  "type": "onsite",
  "consultation_fee_snapshot": 50000,
  "queue_number": 5
}
