@baseUrl = http://localhost:5000/api/v1/appointments
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNDJhNDEyNzktZTliNy00MjBjLTljYmYtMjUyNTQzYzExN2U0Iiwicm9sZSI6InBhdGllbnQiLCJpc3MiOiJtZWRpbGluay1hcHAiLCJleHAiOjE3NjY3MjgxMzYsImlhdCI6MTc2NjY0MTczNn0.akWSr-F558ZWL6UkmbRG9OcOYSEhTSzcWKwUg4PTf04

###
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
   "email": "sdeviation4@gmail.com",
   "password": "SecurePass123"
}

###
GET {{baseUrl}}
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/doctor/d3acd040-75b4-46dc-9cc0-1cbebe986a2b
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/patient/d6dcf46a-6320-4468-8bbc-489e0d2acc19
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/fb206715-cea7-4c3c-b473-35d0e6635414
Authorization: Bearer {{token}}

###
POST {{baseUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "doctor_id": "d3acd040-75b4-46dc-9cc0-1cbebe986a2b",
  "patient_id": "d6dcf46a-6320-4468-8bbc-489e0d2acc19",
  "clinic_id": "253889e5-bacf-4c61-a032-54a340c772f4",
  "appointment_date": "2025-01-10T00:00:00Z",
  "start_time": "2025-01-10T09:00:00Z",
  "end_time": "2025-01-10T09:30:00Z",
  "type": "onsite",
  "consultation_fee_snapshot": 50000,
  "queue_number": 5,
  "meeting_link": "https://zoom.us/j/123456789"
}
