@baseUrl = http://localhost:5000/api/v1/clinics
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNzAwYzg4NzQtMTM3MS00ZWQzLTllMzgtNjFlODYwYTQ3MjM1Iiwicm9sZSI6ImFkbWluIiwiaXNzIjoibWVkaWxpbmstYXBwIiwiZXhwIjoxNzY2NzExMDgzLCJpYXQiOjE3NjY2MjQ2ODN9.EfOAl45EtGMRqxrWJnkRp9Hf_6d8UkU5fqv7C8e48MI

###
POST http://localhost:5000/api/v1/users/login
Content-Type: application/json

{
   "email": "irulxartal@gmail.com",
   "password": "SecurePass123"
}

###
GET {{baseUrl}}/
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/944e7b0e-f8cc-48ef-83f2-44a9b5eff75f
Authorization: Bearer {{token}}

###
POST {{baseUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Klinik Sehat Sentosa",
  "address": "Jl. Merdeka No. 123",
  "city": "Jakarta Selatan",
  "phone_number": "+62-21-5551234",
  "email": "info@kliniksehat.co.id",
  "latitude": -6.260718,
  "longitude": 106.781639,
  "opening_time": {
    "monday":    "09:00-16:00",
    "tuesday":   "09:00-16:00",
    "wednesday": "09:00-16:00",
    "thursday":  "09:00-16:00",
    "friday":    "09:00-16:00",
    "saturday":  "closed",
    "sunday":    "closed"
  },
  "facilities": [
    "UGD",
    "Laboratorium",
    "Apotek",
    "Ruang Tunggu AC"
  ],
  "insurance_partners": [
    "BPJS Kesehatan",
    "Prudential",
    "Allianz"
  ],
  "accreditation": "Paripurna"
}

###
PUT {{baseUrl}}/944e7b0e-f8cc-48ef-83f2-44a9b5eff75f
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Klinik Sehat Sentosa Utama",
  "phone_number": "+62-21-7778889",
  "email": "contact@kliniksehat.co.id",
  "status": "inactive"
}

###
DELETE {{baseUrl}}/944e7b0e-f8cc-48ef-83f2-44a9b5eff75f
Authorization: Bearer {{token}}