@baseUrl = http://localhost:5000/api/v1/doctors
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZGRmNjdkOWUtZTE0NC00MDY3LWEzYmMtMzJjMjFiN2E0ZGMwIiwicm9sZSI6ImRvY3RvciIsImlzcyI6Im1lZGlsaW5rLWFwcCIsImV4cCI6MTc2ODI3NDc4OSwiaWF0IjoxNzY4MTg4Mzg5fQ.HKTFWFls335YJLJ2T-w8cRpjdJy49cRMnLpdvnTf9X0

###
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
   "email": "muhajir@gmail.com",
   "password": "SecurePass123"
}

###
GET {{baseUrl}}/me
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/search?name=

###
GET {{baseUrl}}/d877e585-306e-4cb6-a4e5-69d41b5d2428

###
PUT {{baseUrl}}/0902d466-40c2-4bb7-9884-81035819ebdc
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "specialization": "Dokter Penyakit Dalam"
}

###
GET {{baseUrl}}/schedules?doctor_id=d877e585-306e-4cb6-a4e5-69d41b5d2428
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/schedules/availability?doctor_id=d877e585-306e-4cb6-a4e5-69d41b5d2428&date=2026-01-10&day=monday


###
POST {{baseUrl}}/schedules
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "clinic_id": "03431a76-aed5-4024-a243-23307a07a3d5",
  "day_of_week": "tuesday",
  "start_time": "23:00",
  "end_time": "23:59",
  "max_quota": 20,
  "consultation_fee": 50000,
  "type": "onsite"
}


###
PUT {{baseUrl}}/schedule/93cb8ce5-f5db-49c3-90b0-93ecb0ed79b8
Authorization: Bearer {{token}}
Content-Type: application/json

{
   "day_of_week": "sunday"
}
