@baseUrl = http://localhost:5000/api/v1/doctors
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZWUzYjUzNzItNmNlYy00YjdkLWE5OWEtZGZlNDcxMzYwOWI2Iiwicm9sZSI6ImRvY3RvciIsImlzcyI6Im1lZGlsaW5rLWFwcCIsImV4cCI6MTc2NjgyODE1MSwiaWF0IjoxNzY2NzQxNzUxfQ.oafnq-4s7bZ8zbvFwa6iGjcmb78xfTvfl1NLNmhA8lI

###
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
   "email": "muhajir@gmail.com",
   "password": "SecurePass123"
}

###
GET {{baseUrl}}?name=muhajir

###
GET {{baseUrl}}/d3acd040-75b4-46dc-9cc0-1cbebe986a2b

###
PUT {{baseUrl}}/0902d466-40c2-4bb7-9884-81035819ebdc
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "specialization": "Dokter Penyakit Dalam"
}


###
POST {{baseUrl}}/schedule
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "doctor_id": "d3acd040-75b4-46dc-9cc0-1cbebe986a2b",
  "clinic_id": "253889e5-bacf-4c61-a032-54a340c772f4",
  "day_of_week": "thursday",
  "start_time": "2025-01-15T08:00:00Z",
  "end_time": "2025-01-15T12:00:00Z",
  "max_quota": 20
}


###
PUT {{baseUrl}}/schedule/93cb8ce5-f5db-49c3-90b0-93ecb0ed79b8
Authorization: Bearer {{token}}
Content-Type: application/json

{
   "day_of_week": "sunday"
}
