@baseUrl = http://localhost:5000/api/v1/doctors
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZGRmNjdkOWUtZTE0NC00MDY3LWEzYmMtMzJjMjFiN2E0ZGMwIiwicm9sZSI6ImRvY3RvciIsImlzcyI6Im1lZGlsaW5rLWFwcCIsImV4cCI6MTc2NzgyMzY3MSwiaWF0IjoxNzY3NzM3MjcxfQ.-WH02rW5TYKYt6I6Sl_snFMyRF8QZ2RXySgVy3IW-4Q

###
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
   "email": "muhajir@gmail.com",
   "password": "SecurePass123"
}

###
GET {{baseUrl}}?name=muhajir

###
GET {{baseUrl}}/d3acd040-75b4-46dc-9cc0-1cbebe986a2b

###
PUT {{baseUrl}}/0902d466-40c2-4bb7-9884-81035819ebdc
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "specialization": "Dokter Penyakit Dalam"
}


###
POST {{baseUrl}}/schedules
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "clinic_id": "03431a76-aed5-4024-a243-23307a07a3d5",
  "day_of_week": "thursday",
  "start_time": "08:00",
  "end_time": "12:00",
  "max_quota": 20,
  "consultation_fee": 50000
}


###
PUT {{baseUrl}}/schedule/93cb8ce5-f5db-49c3-90b0-93ecb0ed79b8
Authorization: Bearer {{token}}
Content-Type: application/json

{
   "day_of_week": "sunday"
}
