@baseUrl = http://localhost:5000/api/v1/medicines
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNzAwYzg4NzQtMTM3MS00ZWQzLTllMzgtNjFlODYwYTQ3MjM1Iiwicm9sZSI6ImFkbWluIiwiaXNzIjoibWVkaWxpbmstYXBwIiwiZXhwIjoxNzY2ODAzMjc4LCJpYXQiOjE3NjY3MTY4Nzh9.7x_MHw7C2PhaiPjFFxmdYMgT8v1pHZbL3rru3TapS8Y

###
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
   "email": "irulxartal@gmail.com",
   "password": "SecurePass123"
}
###
GET {{baseUrl}}

###
GET {{baseUrl}}/3e9f0cca-ae47-4fea-9b00-77fe2106232a

###
GET {{baseUrl}}/search?name=Cetirizine

###
POST {{baseUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
   "name": "Vitamin C 1000mg",
   "description": null,
   "generic_name": "Ascorbic Acid",
   "category": "Supplement",
   "manufacturer": null,
   "base_price": 8000,
   "is_prescription_required": false
}

###
PUT {{baseUrl}}/3e9f0cca-ae47-4fea-9b00-77fe2106232a
Authorization: Bearer {{token}}
Content-Type: application/json

{
   "price": 6000
}

###
DELETE {{baseUrl}}/45c8477c-e6c3-4405-986f-861d803a530b
Authorization: Bearer {{token}}