@baseUrl = http://localhost:5000/api/v1/prescriptions
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZGRmNjdkOWUtZTE0NC00MDY3LWEzYmMtMzJjMjFiN2E0ZGMwIiwicm9sZSI6ImRvY3RvciIsImlzcyI6Im1lZGlsaW5rLWFwcCIsImV4cCI6MTc2ODQzMTM5OCwiaWF0IjoxNzY4MzQ0OTk4fQ.fn8ISF0Sm5X0S5M2OK7POxp0AYU80cJoo7aNTlspKUI

###
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
   "email": "muhajir@gmail.com",
   "password": "SecurePass123"
}

###
GET {{baseUrl}}/doctor/d877e585-306e-4cb6-a4e5-69d41b5d2428
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/patient
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/c2cd9f2d-0771-4e72-bb07-3a31d6c372b5
Authorization: Bearer {{token}}

###
POST {{baseUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
   "patient_id": "94c001e2-ea7b-460d-8260-5ed3c0178d05",
   "doctor_id": "d877e585-306e-4cb6-a4e5-69d41b5d2428",
   "medical_record_id": "78135c88-c50a-4923-a5c5-be30ba6ce72a",
   "notes": "Please take the medicine before eating",
   "medicines": [{
      "medicine_id": "2ba03ac8-2c26-477a-9033-1e530374bea0",
      "quantity": 5
   }, {
      "medicine_id": "6c9cd20a-6f98-4a98-9815-50953bc5e96b",
      "quantity": 10
   }]
}

###
PUT {{baseUrl}}/c2cd9f2d-0771-4e72-bb07-3a31d6c372b5
Authorization: Bearer {{token}}
Content-Type: application/json

{
   "notes": "Diminum sebelum makan"
}

###
DELETE {{baseUrl}}/15633889-9aed-456f-bea7-ed5c7f550c4e
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/15633889-9aed-456f-bea7-ed5c7f550c4e/add-medicine
Authorization: Bearer {{token}}
Content-Type: application/json

{
   "prescription_id": "15633889-9aed-456f-bea7-ed5c7f550c4e",
   "medicine_id": "550e423c-8664-441d-a609-9fd022db5213",
   "quantity": 1
}

###
PATCH {{baseUrl}}/15633889-9aed-456f-bea7-ed5c7f550c4e/update-medicine/1656f4f6-720d-4747-a9e2-5563981d2bd8
Authorization: Bearer {{token}}
Content-Type: application/json

{
   "quantity": 1
}

###
DELETE {{baseUrl}}/15633889-9aed-456f-bea7-ed5c7f550c4e/remove-medicine/cd93f779-c6ec-411d-af37-22d6014867c9
Authorization: Bearer {{token}}

