@baseUrl = http://localhost:5000/api/v1/prescriptions
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNTE3NWQ1MzgtZjJjMS00MzhhLWE3N2UtODc4NjFiNjllMWRkIiwicm9sZSI6ImRvY3RvciIsImlzcyI6Im1lZGlsaW5rLWFwcCIsImV4cCI6MTc2NjY0MjAxNCwiaWF0IjoxNzY2NTU1NjE0fQ.WwGKDqWjRUnDWrwEbp2s1m8B15bBBZI4zaxF2zXgMqE

###
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
   "email": "muhajir@gmail.com",
   "password": "SecurePass123"
}

###
GET {{baseUrl}}/doctor
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/patient
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/c2cd9f2d-0771-4e72-bb07-3a31d6c372b5
Authorization: Bearer {{token}}

###
POST {{baseUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
   "patient_id": "97ad4851-9652-4b3c-8653-0e7ce98ebde7",
   "doctor_id": "0902d466-40c2-4bb7-9884-81035819ebdc",
   "notes": "Silahkan diminum setelah makan",
   "medicines": [{
      "medicine_id": "3e9f0cca-ae47-4fea-9b00-77fe2106232a",
      "quantity": 5
   }, {
      "medicine_id": "77019542-1785-4e68-a93e-f5a06a690138",
      "quantity": 10
   }]
}

###
PUT {{baseUrl}}/c2cd9f2d-0771-4e72-bb07-3a31d6c372b5
Authorization: Bearer {{token}}
Content-Type: application/json

{
   "notes": "Diminum sebelum makan"
}

###
DELETE {{baseUrl}}/15633889-9aed-456f-bea7-ed5c7f550c4e
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/15633889-9aed-456f-bea7-ed5c7f550c4e/add-medicine
Authorization: Bearer {{token}}
Content-Type: application/json

{
   "prescription_id": "15633889-9aed-456f-bea7-ed5c7f550c4e",
   "medicine_id": "550e423c-8664-441d-a609-9fd022db5213",
   "quantity": 1
}

###
PATCH {{baseUrl}}/15633889-9aed-456f-bea7-ed5c7f550c4e/update-medicine/1656f4f6-720d-4747-a9e2-5563981d2bd8
Authorization: Bearer {{token}}
Content-Type: application/json

{
   "quantity": 1
}

###
DELETE {{baseUrl}}/15633889-9aed-456f-bea7-ed5c7f550c4e/remove-medicine/cd93f779-c6ec-411d-af37-22d6014867c9
Authorization: Bearer {{token}}

