@baseUrl = http://localhost:5000/api/v1/users
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZThkMzNiMTEtY2RlYS00N2ExLWIxZmUtMGE5YTZhYjhlMTA4Iiwicm9sZSI6InVzZXIiLCJpc3MiOiJtZWRpbGluay1hcHAiLCJleHAiOjE3NjY4NzgyODYsImlhdCI6MTc2Njc5MTg4Nn0.38T9WYQPMtF4aRCD2_cfrWiiyBMEWAHm7wZknbCB1Wk

###
GET {{baseUrl}}/
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/me
Authorization: Bearer {{token}}

###
PUT {{baseUrl}}/
Authorization: Bearer {{token}}
Content-Type: application/json

{
   "first_name": "Johnathan",
   "last_name": "Doe",
   "phone_number": "+6283111037658"
}

###
DELETE {{baseUrl}}/
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/send-verification
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/verify
Authorization: Bearer {{token}}
Content-Type: application/json

{
   "otp": "299557"
}

###
POST {{baseUrl}}/on-board-patient
Authorization: Bearer {{ token }}
Content-Type: application/json

{
  "identity_number": "3171012345100001",
  "birth_date": "1990-05-15",
  "gender": "male",
  "blood_type": "O+",
  "weight_kg": 72,
  "height_cm": 175,
  "allergies": "Seafood, Penicillin",
  "history_chronic_diseases": "None",
  "emergency_contact": "+6281234561790",
  "insurance_provider": "BPJS Kesehatan",
  "insurance_number": "0001234567891",
  "occupation": "Software Engineer"
}
