@baseUrl = http://localhost:5000/api/v1/users
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOWMyMThjMGMtOTFiNS00NmY4LTkyNTItOThlYmY3NTNjMTk5Iiwicm9sZSI6InVzZXIiLCJpc3MiOiJtZWRpbGluay1hcHAiLCJleHAiOjE3NjYwOTk4MjEsImlhdCI6MTc2NjAxMzQyMX0.5mPs77RO2bWOllJXZ25aUK1AT8TE_4b1QjBesbgcniY

###
GET {{baseUrl}}/
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/me
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/register
Content-Type: application/json

{
   "first_name": "Choirul Anam",
   "last_name": "Anam",
   "email": "irulxartal@gmail.com",
   "phone_number": "+6283111037643",
   "password": "SecurePass123",
   "gender": "male",
   "address": "Jl. Kebon Jeruk No. 123",
   "birth_place": "Jakarta",
   "birth_date": "1990-05-15"
}

###
POST {{baseUrl}}/login
Content-Type: application/json

{
   "email": "john.cena@example.com",
   "password": "SecurePass123"
}

###
PUT {{baseUrl}}/
Authorization: Bearer {{token}}
Content-Type: application/json

{
   "first_name": "Johnathan",
   "last_name": "Doe",
   "phone_number": "+6283111037658"
}

###
PATCH {{baseUrl}}/password
Authorization: Bearer {{token}}
Content-Type: application/json

{
   "old_password": "SecurePass123",
   "new_password": "NewSecurePass456"
}

###
DELETE {{baseUrl}}/
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/send-otp
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/verify-otp
Authorization: Bearer {{token}}
Content-Type: application/json

{
   "otp": "630299"
}

###
POST {{baseUrl}}/on-board-patient
Authorization: Bearer {{ token }}
Content-Type: application/json

{
  "identity_number": "3171012345100001",
  "blood_type": "O+",
  "weight_kg": 72,
  "height_cm": 175,
  "allergies": "Seafood, Penicillin",
  "chronic_diseases": "None",
  "emergency_contact": "+6281234561790",
  "insurance_provider": "BPJS Kesehatan",
  "insurance_number": "0001234567891",
  "occupation": "Software Engineer"
}
