@baseUrl = http://localhost:5000/api/v1/users
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNDJhNDEyNzktZTliNy00MjBjLTljYmYtMjUyNTQzYzExN2U0Iiwicm9sZSI6InVzZXIiLCJpc3MiOiJtZWRpbGluay1hcHAiLCJleHAiOjE3NjY3MTEzNDksImlhdCI6MTc2NjYyNDk0OX0.m5w9tSddl5pvCTcnTHbrLty1gc279j7U5tyaGoQx1YQ

###
GET {{baseUrl}}/
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/me
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/register
Content-Type: application/json

{
   "name": "John Cena",
   "email": "john.cena@gmail.com",
   "phone_number": "+6283098037109",
   "password": "SecurePass123"
}

###
POST {{baseUrl}}/login
Content-Type: application/json

{
   "email": "rizaloblolovina@gmail.com",
   "password": "SecurePass123"
}

###
PUT {{baseUrl}}/
Authorization: Bearer {{token}}
Content-Type: application/json

{
   "first_name": "Johnathan",
   "last_name": "Doe",
   "phone_number": "+6283111037658"
}

###
PATCH {{baseUrl}}/password
Authorization: Bearer {{token}}
Content-Type: application/json

{
   "old_password": "SecurePass123",
   "new_password": "NewSecurePass456"
}

###
DELETE {{baseUrl}}/
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/send-otp
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/verify-otp
Authorization: Bearer {{token}}
Content-Type: application/json

{
   "otp": "171443"
}

###
POST {{baseUrl}}/on-board-patient
Authorization: Bearer {{ token }}
Content-Type: application/json

{
  "identity_number": "3171012345100001",
  "birth_date": "1990-05-15",
  "gender": "male",
  "blood_type": "O+",
  "weight_kg": 72,
  "height_cm": 175,
  "allergies": "Seafood, Penicillin",
  "history_chronic_diseases": "None",
  "emergency_contact": "+6281234561790",
  "insurance_provider": "BPJS Kesehatan",
  "insurance_number": "0001234567891",
  "occupation": "Software Engineer"
}
